#!/usr/bin/env bash
# git-signingkey.sh — resolve this machine's GPG signing key and optionally
# write it to the machine-local git include file.
#
#   git-signingkey.sh            print the resolved long key id to stdout
#   git-signingkey.sh --write    also write the include file
#
# Resolution order:
#   1. dotfiles.toml [git] signingkey, if non-empty (explicit pin)
#   2. newest secret key whose uid matches the git identity email
# Exits non-zero with a stderr diagnostic when no key can be resolved.
#
# Test hooks (unset in normal use):
#   GIT_SIGNINGKEY_GPG    path to the gpg binary
#   GIT_SIGNINGKEY_TOML   path to the pin source (dotfiles.toml)
#   GIT_SIGNINGKEY_EMAIL  identity email override
#   GIT_LOCAL_CONFIG      output path for the include file

set -uo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
TOML="${GIT_SIGNINGKEY_TOML:-$REPO/dotfiles.toml}"
LOCAL_GITCONFIG="${GIT_LOCAL_CONFIG:-$HOME/.config/git/local.gitconfig}"
GPG="${GIT_SIGNINGKEY_GPG:-$(command -v gpg2 || command -v gpg || true)}"

RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m'
warn() { echo -e "${YELLOW}[WARN]${NC}  $*" >&2; }
err() { echo -e "${RED}[ERR]${NC}   $*" >&2; }
ok() { echo -e "${GREEN}[OK]${NC}    $*" >&2; }

# read_toml_git <key> — print dotfiles.toml [git] <key>, or nothing.
read_toml_git() {
  [[ -f "$TOML" ]] || return 0
  python3 -c '
import sys
try:
    import tomllib
except ImportError:
    try:
        import toml as tomllib
    except ImportError:
        sys.exit(0)
try:
    data = tomllib.loads(sys.stdin.read())
    v = data.get("git", {}).get(sys.argv[1], "")
    if isinstance(v, str) and v.strip():
        sys.stdout.write(v.strip())
except Exception:
    pass
' "$1" < "$TOML" 2> /dev/null || true
}

identity_email() {
  [[ -n "${GIT_SIGNINGKEY_EMAIL:-}" ]] && {
    printf '%s' "$GIT_SIGNINGKEY_EMAIL"
    return
  }
  local e
  e="$(git config user.email 2> /dev/null || true)"
  [[ -n "$e" ]] && {
    printf '%s' "$e"
    return
  }
  read_toml_git email
}

count_keys() { "$GPG" --list-secret-keys --with-colons "$1" 2> /dev/null | awk -F: '$1=="sec"' | wc -l; }

newest_key() {
  "$GPG" --list-secret-keys --with-colons "$1" 2> /dev/null \
    | awk -F: '$1=="sec"{print $6, $5}' | sort -rn | head -1 | awk '{print $2}'
}

resolve() {
  local pin email key n
  pin="$(read_toml_git signingkey)"
  if [[ -n "$pin" ]]; then
    printf '%s' "$pin"
    return 0
  fi
  email="$(identity_email)"
  [[ -n "$email" ]] || {
    err "no git identity email; set user.email or dotfiles.toml [git] email"
    return 2
  }
  [[ -n "$GPG" && -x "$GPG" ]] || {
    err "gpg not available; pin a key via dotfiles.toml [git] signingkey"
    return 3
  }
  n="$(count_keys "$email")"
  if [[ "$n" -eq 0 ]]; then
    err "no gpg secret key matches $email; pin via dotfiles.toml [git] signingkey"
    return 4
  fi
  key="$(newest_key "$email")"
  [[ "$n" -gt 1 ]] && warn "multiple ($n) gpg keys match $email; using newest $key — pin via dotfiles.toml [git] signingkey to override"
  printf '%s' "$key"
}

write_local() {
  local key="$1"
  mkdir -p "$(dirname "$LOCAL_GITCONFIG")"
  printf '%s\n' \
    "# Generated by dotfiles — machine-local, do not edit by hand." \
    "# Regenerate: dot gpg-sync   (or re-run install.sh)" \
    "[user]" \
    "	signingkey = $key" \
    > "$LOCAL_GITCONFIG"
}

main() {
  local do_write=0
  [[ "${1:-}" == "--write" ]] && do_write=1
  local key rc
  key="$(resolve)"
  rc=$?
  [[ "$rc" -ne 0 ]] && exit "$rc"
  if [[ "$do_write" -eq 1 ]]; then
    write_local "$key"
    ok "Wrote $LOCAL_GITCONFIG (signingkey = $key)"
  else
    printf '%s\n' "$key"
  fi
}

main "$@"
